# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_time', models.CharField(max_length=30)),
                ('current_price', models.CharField(max_length=30)),
                ('price_trend', models.CharField(max_length=10)),
                ('price_volatility', models.CharField(max_length=10)),
                ('click_trend', models.CharField(max_length=10)),
                ('predict_time', models.CharField(max_length=30)),
                ('price_increased', models.CharField(max_length=30)),
                ('actual_price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion_info',
            fields=[
                ('post_num', models.CharField(max_length=10)),
                ('unique_id', models.CharField(max_length=10)),
                ('click', models.CharField(max_length=10)),
                ('like', models.CharField(max_length=10)),
                ('dislike', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
