# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_data_actual_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
