# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion_info',
        ),
    ]
