# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bagging_boosting_knn_logistic_market_pcr_pls_randomforest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bagging',
        ),
        migrations.DeleteModel(
            name='Boosting',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='KNN',
        ),
        migrations.DeleteModel(
            name='Logistic',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='PCR',
        ),
        migrations.DeleteModel(
            name='PLS',
        ),
        migrations.DeleteModel(
            name='RandomForest',
        ),
    ]
